spring:
  application:
    name: FixLocal
  data:
    mongodb:
      uri: mongodb://localhost:27017/fixlocal


jwt:
  secret: T2Zxk9D2c0lXQkVvR2R3c1F0U1Z3Y2RrN3Z4T3p1a2VnRzQ=
  expiration: 86400000


